<?php
require_once __DIR__.'/_bootstrap.php'; require_once __DIR__.'/_layout.php';
$session=sc_require_session();
try{$summary=$sc_repository->summary($session);$unavailable=null;}catch(Throwable $error){$summary=['display_name'=>'','extension'=>$session['extension'],'caller_id'=>'','dids'=>[],'mailbox'=>null,'call_state'=>[]];$unavailable='Some FusionPBX account details are unavailable.';}
$state=$summary['call_state'];$forwarding=[];foreach([['forward_all_enabled','forward_all_destination','Always'],['forward_busy_enabled','forward_busy_destination','When busy'],['forward_no_answer_enabled','forward_no_answer_destination','No answer'],['forward_user_not_registered_enabled','forward_user_not_registered_destination','Not registered']] as [$enabled,$destination,$label]){if(sc_bool($state[$enabled]??false)&&!empty($state[$destination])){$forwarding[]=$label.' → '.$state[$destination];}}
sc_render_header($session,'home','Home');
?>
<?php if($unavailable){?><div class="sc-alert error"><?=sc_escape($unavailable)?></div><?php }?>
<div class="sc-grid two"><section class="sc-card"><h2>Account</h2><div class="sc-value"><?=sc_escape($summary['display_name']?:'Extension '.$summary['extension'])?></div><p class="sc-muted">Extension <?=sc_escape($summary['extension'])?></p></section><section class="sc-card"><h2>Outbound caller ID</h2><div class="sc-value"><?=sc_escape($summary['caller_id']?:'Not configured')?></div><p class="sc-muted"><?=count($summary['dids'])?> direct DID<?=count($summary['dids'])===1?'':'s'?></p></section><section class="sc-card"><h2>Call handling</h2><div class="sc-row"><span>Do not disturb</span><span class="sc-badge"><?=sc_bool($state['do_not_disturb']??false)?'On':'Off'?></span></div><?php if($forwarding){foreach($forwarding as $item){?><p><?=sc_escape($item)?></p><?php }}else{?><p class="sc-muted">No forwarding rules are active.</p><?php }?><p><a href="calls.php">Manage call handling</a></p></section><section class="sc-card"><h2>Voicemail</h2><div class="sc-value"><?=sc_escape($summary['mailbox']??'Unavailable')?></div><p class="sc-muted">FusionPBX mailbox</p><?php if($summary['mailbox']){?><p><a href="voicemail.php">Open voicemail</a></p><?php }?></section></div>
<?php if($summary['dids']){?><div class="sc-divider"></div><section class="sc-card"><h2>Assigned numbers</h2><div class="sc-list"><?php foreach($summary['dids'] as $did){?><div class="sc-row"><span><?=sc_escape($did)?></span><span class="sc-badge">DID</span></div><?php }?></div></section><?php }?>
<?php sc_render_footer(); ?>
